#!/sbin/sh
#
# ViPER4Android 2.5.0.1
#
# Installation prepared by guitardedhero @XDA Developers

mount /system
mount rw,remount /system
mount rw,remount /system /system

OUTFD=/proc/self/fd/$2;
ZIPFILE="$3";
DIR=$(dirname "$ZIPFILE");
ZIP=$3
ViPER=/tmp/zip
AEV=/system/etc/audio_effects_vendor.conf
AOE=/system/vendor/etc/audio_offload_effects.conf
V4A=ViPER4Android
V4APK=ViPER4Android.apk
V4AX86=libv4a_fx_jb_X86.so
V4AARM=libv4a_fx_jb_NEON.so
V4ALIB=libv4a_fx_ics.so
V4AUTL86=x86/libV4AJniUtils.so
V4AUTLARM=armeabi/libV4AJniUtils.so
V4AUTL=/lib/arm/libV4AJniUtils.so
JNI=libV4AJniUtils.so
HTC=/system/etc/htc_audio_effects.conf
API=$(cat /system/build.prop | grep "ro.build.version.sdk=" | dd bs=1 skip=21 count=2)
NAME=$(cat /system/build.prop | grep "ro.product.name=")
NAME=${NAME:16}
ABI=$(grep_prop ro.product.cpu.abi | cut -c-3)
ABILONG=$(grep_prop ro.product.cpu.abi)
=
SPR=set_perm_recursive
CONF=audio_policy.conf
=audio_output_policy.conf
=

ui_print() { echo -e "ui_print $1\nui_print" > $OUTFD; }

set_perm() {
  uid=$1; gid=$2; mod=$3;
  shift 3;
  chown $uid.$gid $*; chown $uid:$gid $*;
  chmod $mod $*;
}

set_perm_recursive() {
  uid=$1; gid=$2; dmod=$3; fmod=$4;
  shift 4;
  until [ ! "$1" ]; do
    chown -R $uid.$gid $1; chown -R $uid:$gid $1;
    find "$1" -type d -exec chmod $dmod {} +;
    find "$1" -type f -exec chmod $fmod {} +;
    shift;
  done;
}

if [ $NAME = angler ] || [ $NAME = bullhead ] || [ $NAME = flounder ]; then
  mount /vendor
  mount rw,remount /vendor
  mount rw,remount /vendor /vendor
fi

ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print "                  ViPER4Android"
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "
ui_print " "

if [ -e /system/etc/audio_effects.conf ]; then
  sed -i '/deep_buffer {/,/}/d' /system/etc/audio_effects.conf
  sed -i '/raw {/,/}/d' /system/etc/audio_effects.conf
fi

if [ -e $SVETC/audio_effects.conf ]; then
  sed -i '/deep_buffer {/,/}/d' $SVETC/audio_effects.conf
  sed -i '/raw {/,/}/d' $SVETC/audio_effects.conf
fi

if [ -e $VETC/audio_effects.conf ]; then
  sed -i '/deep_buffer {/,/}/d' $VETC/audio_effects.conf
  sed -i '/raw {/,/}/d' $VETC/audio_effects.conf
fi

if [ -e $SVETC/audio_output_policy.conf ]; then
  sed -i '/deep_buffer {/,/}/d' $SVETC/audio_output_policy.conf
fi

if [ -e $VETC/audio_output_policy.conf ]; then
  sed -i '/deep_buffer {/,/}/d' $VETC/audio_output_policy.conf
fi

if [ -f $SVETC/audio_policy_configuration.xml ]; then
  sed -i '/deep_buffer {/,/}/d' $SVETC/audio_policy_configuration.xml
  sed -i '/AUDIO_OUTPUT_FLAG_DEEP_BUFFER {/,/}/d' $SVETC/audio_policy_configuration.xml
fi

rm -rf /system/priv-app/$V4A
rm -rf /system/priv-app/ViPER4Android_FX_A4.x
rm -rf /system/app/ViPER4Android_FX_A4.x
rm -rf /system/priv-app/Viper4Android
rm -rf /system/app/$V4A
rm -rf /system/priv-app/AudioFX
rm -rf /system/app/AudioFX
rm -rf /system/priv-app/DSPManager
rm -rf /system/app/DSPManager
rm -rf $V4ADATA
rm -r /system/priv-app/$V4APK
rm -r /system/app/$V4APK
rm -r /system/addon.d/blacklist
rm -r /system/addon.d/50-rr.sh

mkdir $ViPER
cd $ViPER
unzip -o "$ZIP"

CONF=audio_effects.conf

if [ -e /system/etc/audio_effects.conf ]; then
  sed -i '/v4a_fx {/,/}/d' /system/etc/audio_effects.conf
  sed -i '/v4a_standard_fx {/,/}/d' /system/etc/audio_effects.conf
  sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' /system/etc/audio_effects.conf
  sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' /system/etc/audio_effects.conf
fi

if [ -e $SVETC/audio_effects.conf ]; then
  sed -i '/v4a_fx {/,/}/d' $SVETC/audio_effects.conf
  sed -i '/v4a_standard_fx {/,/}/d' $SVETC/audio_effects.conf
  sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' $SVETC/audio_effects.conf
  sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' $SVETC/audio_effects.conf
fi

if [ -e $VETC/audio_effects.conf ]; then
  sed -i '/v4a_fx {/,/}/d' $VETC/audio_effects.conf
  sed -i '/v4a_standard_fx {/,/}/d' $VETC/audio_effects.conf
  sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' $VETC/audio_effects.conf
  sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' $VETC/audio_effects.conf
fi

if [ -e $HTC ]; then
  sed -i '/v4a_fx {/,/}/d' $HTC
  sed -i '/v4a_standard_fx {/,/}/d' $HTC
  sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' $HTC
  sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' $HTC
fi

if [ -e /system/etc/audio_effects_vendor.conf ]; then
  sed -i '/v4a_fx {/,/}/d' /system/etc/audio_effects_vendor.conf
  sed -i '/v4a_standard_fx {/,/}/d' /system/etc/audio_effects_vendor.conf
  sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' /system/etc/audio_effects_vendor.conf
  sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' /system/etc/audio_effects_vendor.conf
fi

if [ -e /system/vendor/etc/audio_offload_effects.conf ]; then
  sed -i '/v4a_fx {/,/}/d' /system/vendor/etc/audio_offload_effects.conf
  sed -i '/v4a_standard_fx {/,/}/d' /system/vendor/etc/audio_offload_effects.conf
  sed -i 's/^libraries {/libraries {\n  v4a_fx {\n    path \/system\/lib\/soundfx\/libv4a_fx_ics.so\n  }/g' /system/vendor/etc/audio_offload_effects.conf
  sed -i 's/^effects {/effects {\n  v4a_standard_fx {\n    library v4a_fx\n    uuid 41d3c987-e6cf-11e3-a88a-11aba5d5c51b\n  }/g' /system/vendor/etc/audio_offload_effects.conf
fi

if [ -e /system/lib64 ]; then
  mkdir -p /system/lib64/soundfx
  cp $CL64/soundfx/libeffectproxy.so /system/lib64/soundfx/libeffectproxy.so
  set_perm_recursive 0 0 0755 0644 /system/lib64/soundfx
fi

if [ $API -ge 21 ]; then
  mkdir -p /system/priv-app/$V4A
  mkdir -p /system/priv-app/$V4A/lib/arm
  mkdir -p /system/su.d
  cp -rf viper/* /system
  cp customize/su.d/soundserver /system/su.d/soundserver
  cp customize/app/$V4APK /system/priv-app/$V4A/$V4APK
  if [ $ABI = x86 ] || [ $ABILONG = x86_64 ]; then
    cp customize/app/$V4AUTL86 /system/priv-app/$V4A$V4AUTL
    cp customize/app/$V4AUTL86 /system/lib/$JNI
    cp customize/lib/$V4A86 /system/lib/soundfx/$V4ALIB
  else
    cp customize/app/$V4AUTLARM /system/priv-app/$V4A$V4AUTL
    cp customize/app/$V4AUTLARM /system/lib/$JNI
    cp customize/lib/$V4AARM /system/lib/soundfx/$V4ALIB
  fi
  set_perm_recursive 0 0 0755 0755 /system/su.d
  set_perm_recursive 0 0 0755 0644 /system/priv-app/$V4A
  set_perm 0 0 0644 /system/lib/soundfx/$V4ALIB
  set_perm 0 0 0644 /system/lib/soundfx/libeffectproxy.so
  set_perm 0 0 0644 /system/lib/$JNI
fi

if [ $API -lt 21 ]; then
  cp -rf viper/* /system
  cp customize/app/$V4APK /system/app/$V4APK
  if [ $ABI -eq x86 ]; then
    cp customize/app/$V4AUTL86 /system/lib/$JNI
    cp customize/lib/$V4A86 /system/lib/soundfx/$V4ALIB
  else
    cp customize/app/$V4AUTLARM /system/lib/$JNI
    cp customize/lib/$V4AARM /system/lib/soundfx/$V4ALIB
  fi
  set_perm 0 0 0644 /system/app/$V4APK
  set_perm 0 0 0644 /system/lib/$JNI
  set_perm 0 0 0644 /system/lib/soundfx/$V4ALIB
  set_perm 0 0 0644 /system/lib/soundfx/libeffectproxy.so
fi

rm -rf $ViPER

umount /system

if [ $NAME = angler ] || [ $NAME = bullhead ] || [ $NAME = flounder ]; then
  umount /vendor
fi

sleep 4

exit 0
